#ifndef OSMIUM_OSM_NODE_HPP
#define OSMIUM_OSM_NODE_HPP

/*

This file is part of Osmium (https://osmcode.org/libosmium).

Copyright 2013-2022 Jochen Topf <jochen@topf.org> and others (see README).

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#include <osmium/memory/item.hpp>
#include <osmium/osm/item_type.hpp>
#include <osmium/osm/location.hpp>
#include <osmium/osm/object.hpp>

#include <tl/optional.hpp>
// std::optional for c++11
// you can use std::unique_ptr<T>

namespace osmium {
    namespace builder {
        template <typename TDerived, typename T>
        class OSMObjectBuilder;
    } // namespace builder

    class Node : public OSMObject {

        template <typename TDerived, typename T>
        friend class osmium::builder::OSMObjectBuilder;

        struct Cache {
            tl::optional<double> elevation;
            tl::optional<RowVectors> key_points;
        };

        osmium::Location m_location;
        mutable tl::optional<Cache> cache;

        void auto_caching() const {
            if (cache) {
                return;
            }
            cache = Cache{};
            for (auto &tag: tags()) {
                // https://wiki.openstreetmap.org/wiki/Altitude
                if (!std::strcmp(tag.key(), "ele")) {
                    // <tag k="ele" v="21.228"/>
                    double ele = std::atof(tag.value());
                    cache->elevation = ele;
                    // m_location.set_alt(ele);
                }
            }
        }

        Node() :
            OSMObject(sizeof(Node), osmium::item_type::node) {
        }

    public:

        static constexpr osmium::item_type itemtype = osmium::item_type::node;

        constexpr static bool is_compatible_to(osmium::item_type t) noexcept {
            return t == itemtype;
        }

        tl::optional<double> elevation() const {
            auto_caching();
            return cache->elevation;
        }

        osmium::Location location() const noexcept {
            auto_caching();
            return m_location;
        }

        Node& set_location(const osmium::Location& location) noexcept {
            m_location = location;
            return *this;
        }

    }; // class Node

    static_assert(sizeof(Node) % osmium::memory::align_bytes == 0, "Class osmium::Node has wrong size to be aligned properly!");

} // namespace osmium

#endif // OSMIUM_OSM_NODE_HPP
